# Module 3
#   Programming Assignment 4
#     Prob-5.py

# <Jeremy>

def main():
    try:
         x = eval(2)
         
    except:
        print("There was a eval 2 error. Exiting.")
        exit


main()